version: "3"

tasks:
  dev:
    cmds:
      - pnpm dev

  build:
    cmds:
      - pnpm build

  build:clean:
    cmds:
      - |
        rm -rf .vimxi
        rm -rf .output

  db:up:
    cmds:
      - bash ./scripts/db_up.sh

  db:gen:
    cmds:
      - pnpm db:generate

  db:migrate:
    cmds:
      - pnpm db:migrate
